version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
