language: node_js
node_js:
  - 14
install:
  - npm ci
  - (cd example && npm install)
script:
  - npm test
  - npm run build
  - (cd example && npm test)
  - (cd example && npm run build)
deploy:
  - provider: pages:git
    edge: true
    cleanup: false
    token: $GITHUB_TOKEN
    local_dir: example/build
    on:
      tags: true
  - provider: releases
    edge: true
    api_key: $GITHUB_TOKEN
    file: "README.md"
    on:
      tags: true
  - provider: npm
    cleanup: false
    api_token: $NPM_API_TOKEN
    edge: true
    on:
      tags: true
