name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - run: npm ci
      - run: (cd example && npm install)
      - run: npm run build
      - run: (cd example && npm test)
      - run: (cd example && npm run build)
