name: release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org/"
      - run: npm ci
      - run: (cd example && npm install)
      - run: npm run build
      - run: (cd example && npm test)
      - run: (cd example && npm run build)
      - name: Publish package on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./example/build"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md"
